apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  rules:
  - host: frontend.onprem.cloudcomputingassociates.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 443
  tls:                                # add next 4 lines for TLS on ingress
  - hosts:                            
      - frontend.onprem.cloudcomputingassociates.net
    secretName: ingress-tls     # Did you create your secret?
